runtime: nodejs24
service: unisafe-api 

entrypoint: node dist/index.js

env_variables:
  DATABASE_URL: "mysql://user-db:%40Evia%2A%2A2021@localhost/UniSafe?socket=/cloudsql/evia-app:us-central1:evia-db"
                 
  JWT_SECRET: "sindicato-super-secret-jwt-key-change-this-in-production"
  NODE_ENV: "production"
  CORS_ORIGIN: "https://unisafe.evia.com.br"
  VITE_API_URL: "https://unisafe-api-dot-evia-app.ue.r.appspot.com"
  TZ: "America/Sao_Paulo"
  ENVIRONMENT: "False"

# Bucket (Wasabi)
BUCKET_NAME: "unisafe"
AWS_ACCESS_KEY_ID: "DFGF37GY9UVPGF0PFW2Q"
AWS_SECRET_ACCESS_KEY: "yNuXM5u6riUl7YBKsDY7FRBCVCziBRjV6VJgQf9I"
BUCKET_REGION: "us-east-1"
BUCKET_ENDPOINT: "https://s3.wasabisys.com"

beta_settings:
  cloud_sql_instances: evia-app:us-central1:evia-db

automatic_scaling:
  max_instances: 1