# Cloud Build para UniSafe Backend
steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/unisafe-backend:$COMMIT_SHA', '.']
    dir: 'backend'

  # Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/unisafe-backend:$COMMIT_SHA']

  # Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'unisafe-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/unisafe-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Imagens que serão criadas
images:
  - 'gcr.io/$PROJECT_ID/unisafe-backend:$COMMIT_SHA'

# Timeout do build
timeout: '1200s'
